### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by yeethuan** [yeethuan/idm-221-yy559#2]
@philsinatra sorry about that

My margins in my Portfolio page and my Gallery page are inconsistent with each other. Additionally, the images are not centered and I do not know how to
1. have images centered WITH left and right margins of 15px 
2. images that scale with the screen

In my css they are all defined by "margin-left: 15px; and "margin-right: 15px;". I believe the issue stems from my horizontal images that are bigger than the screens causing a mandatory horizontal scroll. I do not know how to resolve either issues.

https://idmyy559.netlify.app/

**Comment by philsinatra** [comment]
https://github.com/yeethuan/idm-221-yy559/blob/1e33ff63d81326ada2f00cd2f52420d5b64ce0bc/portfolio.css#L131

You should set the `width` for your images to `100%`. You can remove the `max-width` property, and I would also eliminate the `margin` values on the left and right. If you want `15px` of space on the left and right, add a `margin` or `padding` to a container and place the images in the container. This approach will give you more control in case there are situations in which you need an image but don't want the margin.

You can horizontally center content using the `margin` property with a value of `auto.` Use this approach in conjunction with the `width` adjustments and you should be able to solve both problems.

**Comment by yeethuan** [comment]
thank you so much!!
